rootProject.name = "LearnRabbitMQ"
include("rabbit-utils")
include("rabbit-01")
include("rabbit-02")
include("rabbit-03")
include("rabbit-04")
include("rabbit-05")
include("rabbit-06")
include("rabbit-07")
include("rabbit-08")
include("rabbit-09")
include("rabbit-10")
include("rabbit-11")
include("rabbit-12")
